abstract: Library for enabling X-WSSE authentication in LWP
author: Audrey Tang <audrey@audrey.org>
distribution_type: module
generated_by: Module::Install version 0.50
license: perl
name: LWP-Authen-Wsse
no_index:
  directory:
    - inc
    - t
requires:
  Digest::SHA1: 0
  LWP: 0
  MIME::Base64: 0
  perl: 5.004
version: 0.05
