name: LWP-Authen-Wsse
version: 0.03
abstract: Library for enabling X-WSSE authentication in LWP
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  LWP: 0
  Digest::SHA1: 0
  MIME::Base64: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
